# Use a base Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install the required packages
COPY requirements-serve-model.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the local files to the container
COPY pythonscripts/serve_model.py serve_model.py

# Command to run the Python script
CMD ["python", "serve_model.py"]
