apiVersion: batch/v1
kind: Job
metadata:
  name: random-forest-job-1
spec:
  template:
    spec:
      containers:
      - name: random-forest
        image: ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.MODEL_IMAGE_NAME }}:${{ github.sha }}
        args: ["--hyperparameters", "n_estimators=50,max_depth=5"]
        volumeMounts:
        - name: my-persistent-storage
          mountPath: /data  # This is where the container will access the persistent storage
      restartPolicy: Never
      volumes:
      - name: my-persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
