apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  name: random-forest-experiment
  namespace: kubeflow
spec:
  objective:
    type: minimize
    goal: 0.01
    objectiveMetricName: mean_squared_error
  algorithm:
    algorithmName: random
  parameters:
    - name: --n_estimators
      parameterType: int
      feasibleSpace:
        min: "50"
        max: "150"
    - name: --max_depth
      parameterType: int
      feasibleSpace:
        min: "5"
        max: "20"
  trialTemplate:
    primaryContainerName: random-forest
    trialParameters:
      - name: --n_estimators
        description: "Number of trees"
        reference: --n_estimators
      - name: --max_depth
        description: "Maximum tree depth"
        reference: --max_depth
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: random-forest
                image: ghcr.io/sujansharma07/random-forest-tuner:latest
                command: ["python", "train.py"]
                args:
                  - "--n_estimators"
                  - "{{trialParameters.--n_estimators}}"
                  - "--max_depth"
                  - "{{trialParameters.--max_depth}}"
                volumeMounts:
                  - name: output
                    mountPath: /output
            volumes:
              - name: output
                hostPath:
                  path: /mnt/results  
            restartPolicy: Never
